### ISSUE TITLE
base64 decode parameter varies across platforms

### ISSUE THREAD

**Issue by oligond** [emcrisostomo/jwt-cli#1]
As the short form of the base64 `--decode` option is different between the GNU version (`-d`)and the version shipped with OSX (`-D`), it might be preferable to just use the long form `--decode` in the script as it equally works for both `base64` implementations.
On my Fedora system, the script didn't work out of the box because of using the short form not accepted by the GNU version.
See also:
[GNU base64 manpage](https://www.gnu.org/software/coreutils/manual/html_node/base64-invocation.html) vs. [OSX base64 manpage](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/base64.1.html)
PR coming.

**Comment by emcrisostomo** [comment]
Thanks for the PR @Alcofribas.
